name: Update LeetCode Stats

on:
  schedule:
    - cron: '0 0 * * *' # Runs automatically every day at midnight
  workflow_dispatch: # Allows you to run it manually anytime

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Update LeetCode Stats inside README
        uses: joshcai/leetcode-sync@v1.1
        with:
          username: adhiviraj
          style: tokyonight # Matches your aesthetic perfectly
