name: Generate Snake

on:
  # Automatically runs every day at midnight UTC
  schedule:
    - cron: "0 0 * * *"
  
  # Keeps the manual "Run workflow" button in your Actions tab
  workflow_dispatch:

  # Optional: Also runs whenever you push changes to your main branch
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Adhiviraj
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
